apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: masterizando-stage
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/gilsonrusso/argocd-trainning.git
    targetRevision: main
    path: .
    helm:
      valueFiles:
        - values.yaml
        - values.stage.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
